import { ArrowRight, BarChart3, Bot, CheckCircle2, MapPin, ShieldCheck, Sparkles, TrendingUp } from 'lucide-react';
import { buttonVariants } from '@/components/ui/button';
import { cn } from '@/lib/utils';

const products = [
  { name: 'FanXtra', subtitle: 'Yaourt glacé enrichi en vitamines et sels minéraux.', image: '/fan-site/fanxtra.png', badge: 'Glacé', tint: 'from-sky-100 to-blue-50' },
  { name: 'FanYogo', subtitle: 'Yaourt écrémé aromatisé à la fraise, frais et gourmand.', image: '/fan-site/fanyogo.png', badge: 'Fraise', tint: 'from-pink-100 to-rose-50' },
  { name: 'FanChoco', subtitle: 'La gourmandise chocolatée au goût intense de cacao.', image: '/fan-site/fanchoco.jpg', badge: 'Cacao', tint: 'from-orange-100 to-amber-50' },
  { name: 'FanVanille', subtitle: 'Boisson lactée à la vanille, crémeuse et délicieuse.', image: '/fan-site/fanvanille.png', badge: 'Vanille', tint: 'from-yellow-100 to-amber-50' },
  { name: 'FanIce', subtitle: 'Crème glacée à la vanille, la pause fraîcheur.', image: '/fan-site/fanice.png', badge: 'Glace', tint: 'from-cyan-100 to-blue-50' },
  { name: 'FanDango', subtitle: 'Boisson citrus pétillante et rafraîchissante.', image: '/fan-site/fandango.png', badge: 'Nouveau', tint: 'from-lime-100 to-yellow-50' },
];

export default function Home() {
  return (
    <main className="overflow-hidden bg-white text-[#122043]">
      <header className="fixed inset-x-0 top-0 z-50 border-b border-blue-950/6 bg-white/85 backdrop-blur-xl">
        <div className="mx-auto flex h-20 max-w-7xl items-center justify-between px-5 lg:px-8">
          <a href="#accueil" className="flex items-center gap-3"><img src="/fan-site/logo.png" alt="Logo FanMilk" className="h-14 w-auto object-contain" /></a>
          <nav className="hidden items-center gap-8 text-sm font-extrabold text-[#122043] md:flex"><a href="#bienfaits" className="hover:text-[#0a4ea8]">Nos atouts</a><a href="#produits" className="hover:text-[#0a4ea8]">Produits</a><a href="#dashboard" className="hover:text-[#0a4ea8]">Dashboard</a><a href="#contact" className="hover:text-[#0a4ea8]">Contact</a></nav>
          <a href="/connexion" className={cn(buttonVariants({ size: 'lg' }), 'rounded-full bg-[#0a4ea8] px-6 font-black text-white shadow-lg shadow-blue-900/20 hover:bg-[#082f70]')}>Se connecter <ArrowRight /></a>
        </div>
      </header>

      <section id="accueil" className="relative min-h-[760px] bg-[linear-gradient(155deg,#cfeaff_0%,#eef8ff_42%,#ffffff_68%,#fff8da_100%)] pt-20 lg:min-h-screen">
        <div className="fan-blob absolute -left-36 -top-24 size-[520px] rounded-full bg-sky-300/30 blur-2xl" /><div className="fan-blob absolute -bottom-40 right-0 size-[430px] rounded-full bg-yellow-200/45 blur-3xl [animation-delay:-4s]" />
        <div className="mx-auto grid min-h-[680px] max-w-7xl items-center gap-8 px-5 py-16 lg:grid-cols-[.9fr_1.1fr] lg:px-8">
          <div className="relative z-10 max-w-2xl"><p className="mb-4 text-xs font-black uppercase tracking-[.24em] text-[#0a4ea8]">FanMilk Togo</p><h1 className="text-[clamp(4rem,8vw,7.4rem)] font-black leading-[.78] tracking-[-.075em] text-[#082f70]">Délicieux,<br /><span className="text-[#0a5bb5]">Onctueux.</span></h1><p className="mt-8 max-w-xl text-lg font-semibold leading-8 text-slate-600">La fraîcheur FanMilk tous les jours : yaourts, boissons lactées et crèmes glacées à savourer en famille ou entre amis.</p><div className="mt-9 flex flex-wrap gap-3"><a href="#produits" className={cn(buttonVariants({ size: 'lg' }), 'h-13 rounded-full bg-[#0a4ea8] px-7 text-base font-black hover:bg-[#082f70]')}>Voir nos produits <ArrowRight /></a><a href="/connexion" className={cn(buttonVariants({ variant: 'outline', size: 'lg' }), 'h-13 rounded-full border-2 border-[#0a4ea8] bg-white/70 px-7 text-base font-black text-[#0a4ea8]')}>Accéder au Dashboard</a></div></div>
          <div className="relative min-h-[470px] lg:min-h-[610px]"><div className="absolute inset-[10%] rounded-full bg-white/65 shadow-[0_40px_100px_rgba(10,58,145,.14)]" /><img src="/fan-site/yaourt-vanille.png" alt="Yaourt vanille FanMilk" className="fan-float-one absolute right-0 top-4 z-10 w-[66%] drop-shadow-[0_35px_30px_rgba(10,58,145,.24)]" /><img src="/fan-site/yaourt-nature.png" alt="Yaourt nature FanMilk" className="fan-float-two absolute bottom-0 left-0 z-20 w-[61%] drop-shadow-[0_35px_30px_rgba(10,58,145,.24)]" /><span className="absolute bottom-8 right-2 z-30 rounded-2xl bg-white/90 px-5 py-4 shadow-xl backdrop-blur"><strong className="block text-2xl font-black text-[#082f70]">130 g</strong><span className="text-xs font-bold text-slate-500">Source de calcium</span></span></div>
        </div>
      </section>

      <section id="bienfaits" className="px-5 py-24 lg:px-8"><div className="mx-auto grid max-w-6xl items-center gap-14 lg:grid-cols-[.85fr_1.15fr]"><div><p className="text-xs font-black uppercase tracking-[.22em] text-[#0a5bb5]">Pourquoi FanXtra</p><h2 className="mt-4 text-4xl font-black leading-tight tracking-tight text-[#082f70]">Un yaourt glacé pensé pour votre bien-être</h2><p className="mt-5 text-lg leading-8 text-slate-600">Enrichi en vitamines et sels minéraux pour accompagner votre journée, sans jamais sacrifier le goût.</p><div className="mt-7 grid grid-cols-2 gap-3">{['Vitamine B6', 'Phosphore', 'Calcium', 'Iode'].map((item) => <span key={item} className="flex items-center gap-2 rounded-2xl bg-blue-50 p-3 text-sm font-black text-[#0a4ea8]"><CheckCircle2 className="size-4" />{item}</span>)}</div></div><div className="relative rounded-[40px] bg-[radial-gradient(circle,#e5f5ff,transparent_70%)] p-8"><img src="/fan-site/fanxtra.png" alt="FanXtra" className="mx-auto w-full max-w-xl drop-shadow-[0_30px_30px_rgba(10,58,145,.2)]" /></div></div></section>

      <section className="bg-[#082f70] px-5 py-20 text-white lg:px-8"><div className="mx-auto grid max-w-7xl items-center gap-12 lg:grid-cols-[1.15fr_.85fr]"><img src="/fan-site/promo-banner.jpg" alt="Yaourts FanMilk nature et vanille" className="w-full -rotate-1 rounded-[30px] shadow-2xl" /><div><p className="text-xs font-black uppercase tracking-[.22em] text-yellow-300">Nos yaourts</p><h2 className="mt-4 text-4xl font-black">Nature & Vanille</h2><p className="mt-5 text-lg leading-8 text-blue-100/80">Onctueux, source de calcium, en pot individuel de 130 g. Le geste sain et gourmand à tout moment.</p><a href="#produits" className={cn(buttonVariants({ size: 'lg' }), 'mt-7 rounded-full bg-white px-7 font-black text-[#082f70] hover:bg-yellow-100')}>Découvrir la gamme</a></div></div></section>

      <section id="produits" className="bg-[#f8fbff] px-5 py-24 lg:px-8"><div className="mx-auto max-w-7xl"><div className="mx-auto max-w-2xl text-center"><p className="text-xs font-black uppercase tracking-[.22em] text-[#0a5bb5]">Notre gamme</p><h2 className="mt-4 text-4xl font-black tracking-tight text-[#082f70]">Un FanMilk pour chaque envie</h2></div><div className="mt-12 grid gap-6 sm:grid-cols-2 lg:grid-cols-3">{products.map((product) => <article key={product.name} className={`group relative overflow-hidden rounded-[30px] bg-gradient-to-br ${product.tint} p-6 shadow-sm ring-1 ring-blue-950/6 transition-all hover:-translate-y-2 hover:shadow-xl`}><span className="absolute right-5 top-5 rounded-full bg-[#082f70] px-3 py-1 text-[10px] font-black uppercase tracking-wider text-white">{product.badge}</span><div className="grid h-52 place-items-center"><img src={product.image} alt={product.name} className="max-h-44 w-full object-contain drop-shadow-xl transition-transform duration-500 group-hover:scale-110 group-hover:-rotate-2" /></div><h3 className="mt-3 text-2xl font-black text-[#082f70]">{product.name}</h3><p className="mt-2 min-h-12 text-sm font-semibold leading-6 text-slate-600">{product.subtitle}</p></article>)}</div></div></section>

      <section id="dashboard" className="px-5 py-24 lg:px-8"><div className="mx-auto grid max-w-7xl overflow-hidden rounded-[40px] bg-[#082f70] text-white shadow-2xl shadow-blue-950/20 lg:grid-cols-[.82fr_1.18fr]"><div className="p-9 lg:p-14"><p className="text-xs font-black uppercase tracking-[.22em] text-yellow-300">Côté Dashboard</p><h2 className="mt-4 text-4xl font-black tracking-tight">Suivez les ventes de toute la gamme.</h2><p className="mt-5 leading-7 text-blue-100/75">Le Vendor Bot collecte les déclarations terrain. Le Dashboard affiche les ventes, les stocks, les revendeurs et la performance de chaque produit.</p><div className="mt-7 space-y-3 text-sm font-bold">{[{ icon: Bot, text: 'Déclarations WhatsApp automatisées' }, { icon: TrendingUp, text: 'Ventes et objectifs en temps réel' }, { icon: ShieldCheck, text: 'Accès sécurisé et données centralisées' }].map(({ icon: Icon, text }) => <p key={text} className="flex items-center gap-3"><span className="grid size-9 place-items-center rounded-xl bg-white/10"><Icon className="size-4 text-yellow-300" /></span>{text}</p>)}</div><a href="/connexion" className={cn(buttonVariants({ size: 'lg' }), 'mt-8 rounded-full bg-yellow-300 px-7 font-black text-[#082f70] hover:bg-yellow-200')}>Ouvrir le Dashboard <ArrowRight /></a></div><div className="bg-[#eef7ff] p-5 text-[#122043] lg:p-8"><div className="rounded-[28px] bg-white p-5 shadow-xl"><div className="flex items-center justify-between"><div><p className="text-xs font-black uppercase tracking-wider text-slate-400">Vue générale</p><p className="mt-1 font-black text-[#082f70]">Activité commerciale</p></div><span className="rounded-full bg-blue-50 px-3 py-1 text-xs font-black text-[#0a5bb5]">En direct</span></div><div className="mt-5 grid grid-cols-2 gap-3">{[{ icon: BarChart3, label: 'Ventes du jour', value: '428 500', unit: 'FCFA' }, { icon: Sparkles, label: 'Produits vendus', value: '286', unit: 'unités' }, { icon: MapPin, label: 'Dépôts actifs', value: '12', unit: 'zones' }, { icon: TrendingUp, label: 'Objectif mensuel', value: '78', unit: '%' }].map(({ icon: Icon, label, value, unit }) => <div key={label} className="rounded-2xl bg-[#f5f9ff] p-4"><Icon className="size-5 text-[#0a5bb5]" /><p className="mt-4 text-xs font-bold text-slate-500">{label}</p><p className="mt-1 text-2xl font-black text-[#082f70]">{value} <span className="text-[10px] text-slate-400">{unit}</span></p></div>)}</div><div className="mt-4 rounded-2xl bg-[#082f70] p-5 text-white"><p className="text-xs font-bold text-blue-100/60">Progression des ventes</p><div className="mt-5 flex h-24 items-end gap-2">{[30,48,42,70,58,84,66,92,76,100].map((height, index) => <span key={index} className="flex-1 rounded-t bg-sky-300" style={{ height: `${height}%` }} />)}</div></div></div></div></div></section>

      <section className="bg-[#f7fbff] px-5 py-20 lg:px-8"><div className="mx-auto grid max-w-7xl items-center gap-10 lg:grid-cols-[1.15fr_.85fr]"><img src="/fan-site/full-range.jpg" alt="Gamme complète FanMilk" className="w-full rounded-[30px] shadow-xl" /><div><p className="text-xs font-black uppercase tracking-[.22em] text-[#0a5bb5]">La collection complète</p><h2 className="mt-4 text-4xl font-black text-[#082f70]">Et bien plus encore</h2><p className="mt-5 text-lg leading-8 text-slate-600">Yaourts, boissons lactées et crèmes glacées : la famille FanMilk ne cesse de s’agrandir.</p></div></div></section>

      <footer id="contact" className="bg-[#061f4e] px-5 py-12 text-white lg:px-8"><div className="mx-auto flex max-w-7xl flex-col gap-8 sm:flex-row sm:items-center sm:justify-between"><div><img src="/fan-site/logo.png" alt="FanMilk" className="h-20 rounded-xl bg-white p-2" /><p className="mt-4 text-sm text-blue-100/60">Délicieux, Onctueux. La fraîcheur FanMilk, tous les jours.</p></div><div className="text-sm text-blue-100/70"><p className="font-black text-yellow-300">FanMilk Togo</p><p className="mt-2">Zone Industrielle, Lomé, Togo</p><p className="mt-1">© 2026 FanMilk. Tous droits réservés.</p></div></div></footer>
    </main>
  );
}
