'use client';

import { FormEvent, useState } from 'react';
import { AlertTriangle, Award, BarChart3, Bell, Building2, CircleDollarSign, Database, LogOut, Plus, Settings, ShoppingCart, Users } from 'lucide-react';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';

type Account = { id: number; name: string; email: string; role: 'administrateur' | 'depositaire' | 'revendeur'; depot: string; phone?: string; active: boolean };
type Issue = { id: number; seller: string; depot: string; category: string; description: string; date: string; state: 'ouverte' | 'en_cours' | 'resolue' };

const initialAccounts: Account[] = [
  { id: 1, name: 'Admin FanMilk', email: 'admin@fanmilk.tg', role: 'administrateur', depot: 'Vue nationale', active: true },
  { id: 2, name: 'Kodjo Amégan', email: 'kodjo@fanmilk.tg', role: 'depositaire', depot: 'SUPER DEPOT', active: true },
  { id: 3, name: 'Ama Kossi', email: 'ama.rev@fanmilk.tg', role: 'revendeur', depot: 'SUPER DEPOT', phone: '22890112438', active: true },
];

const performances = [
  { seller: 'Ama Kossi', depot: 'SUPER DEPOT', amount: '682 500', score: 92, average: 78, period: 'Août 2026', suggested: 35000 },
  { seller: 'Dédévi Afi', depot: 'GERM DOSSEH', amount: '641 000', score: 88, average: 76, period: 'Août 2026', suggested: 30000 },
  { seller: 'Yao Mensah', depot: 'SUPER DEPOT', amount: '541 000', score: 84, average: 78, period: 'Août 2026', suggested: 25000 },
];

const initialIssues: Issue[] = [
  { id: 81, seller: 'Dédévi Afi', depot: 'GERM DOSSEH', category: 'Équipement', description: 'Glacière endommagée pendant la tournée.', date: '28 août', state: 'ouverte' },
  { id: 80, seller: 'Yao Mensah', depot: 'SUPER DEPOT', category: 'Produit', description: 'Rupture FanChoco sur la zone.', date: '27 août', state: 'en_cours' },
];

const globalRows = [
  { type: 'Vente', ref: 'V-1042', seller: 'Ama Kossi', depot: 'SUPER DEPOT', detail: '48 500 FCFA', status: 'en_attente' },
  { type: 'Stock', ref: 'S-301', seller: 'Ama Kossi', depot: 'SUPER DEPOT', detail: 'FXT · 22 unités', status: 'en_attente' },
  { type: 'Vente', ref: 'V-1038', seller: 'Dédévi Afi', depot: 'GERM DOSSEH', detail: '62 000 FCFA', status: 'validee' },
];

export default function DashboardPage() {
  const [accounts, setAccounts] = useState(initialAccounts);
  const [issues, setIssues] = useState(initialIssues);
  const [showAccountForm, setShowAccountForm] = useState(false);
  const [prize, setPrize] = useState<(typeof performances)[number] | null>(null);
  const [prizeAmount, setPrizeAmount] = useState('');
  const [notice, setNotice] = useState('');

  function createAccount(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); const form = new FormData(event.currentTarget); const role = form.get('role') as Account['role'];
    setAccounts((rows) => [...rows, { id: Date.now(), name: String(form.get('name')), email: String(form.get('email')), role, depot: role === 'administrateur' ? 'Vue nationale' : String(form.get('depot')), phone: String(form.get('phone') || ''), active: true }]);
    setShowAccountForm(false); setNotice('Compte créé. Les identifiants temporaires peuvent maintenant être communiqués à l’utilisateur.');
  }

  function nextIssueState(id: number) { setIssues((rows) => rows.map((row) => row.id !== id ? row : { ...row, state: row.state === 'ouverte' ? 'en_cours' : 'resolue' })); setNotice('État de la difficulté enregistré.'); }
  function assignPrize() { if (!prize || !Number(prizeAmount)) return; setNotice(`Prime de ${Number(prizeAmount).toLocaleString('fr-FR')} FCFA attribuée à ${prize.seller}. Une notification sera envoyée.`); setPrize(null); setPrizeAmount(''); }

  return (
    <main className="min-h-screen bg-[#f3f7fb] text-[#122043] lg:grid lg:grid-cols-[250px_1fr]">
      <aside className="hidden min-h-screen flex-col bg-[#073b86] px-4 py-5 text-white lg:flex"><a href="/" className="flex items-center gap-3 px-2"><img src="/fan-site/logo-clean.png" alt="FanMilk" className="h-12 w-15 object-contain" /><span><strong className="block text-sm italic">FanMilk Togo</strong><small className="text-[10px] uppercase tracking-[.16em] text-blue-100/60">Administration nationale</small></span></a><nav className="mt-10 space-y-1 text-sm font-bold">{[{ href: '#indicateurs', label: 'Pilotage national', icon: BarChart3 },{ href: '#comptes', label: 'Comptes utilisateurs', icon: Users },{ href: '#performances', label: 'Performances & primes', icon: Award },{ href: '#difficultes', label: 'Difficultés PRIME', icon: AlertTriangle },{ href: '#donnees', label: 'Ventes & stocks', icon: Database }].map(({ href, label, icon: Icon },index) => <a key={label} href={href} className={`flex items-center gap-3 rounded-xl px-3 py-3 ${index === 0 ? 'bg-white text-[#073b86]' : 'text-blue-100/70 hover:bg-white/10 hover:text-white'}`}><Icon className="size-4" />{label}</a>)}</nav><div className="mt-auto border-t border-white/10 pt-4"><a href="#" className="flex items-center gap-3 rounded-xl px-3 py-2.5 text-sm font-semibold text-blue-100/65"><Settings className="size-4" />Paramètres</a><a href="/connexion" className="mt-1 flex items-center gap-3 rounded-xl px-3 py-2.5 text-sm font-semibold text-blue-100/65"><LogOut className="size-4" />Déconnexion</a></div></aside>
      <section className="min-w-0"><header className="sticky top-0 z-50 flex min-h-20 items-center justify-between border-b border-blue-950/8 bg-white/95 px-5 backdrop-blur lg:px-8"><div><strong className="block text-sm text-[#082f70]">Vue nationale</strong><span className="text-xs text-slate-500">Aucun filtre de dépôt imposé</span></div><div className="flex items-center gap-3"><Badge className="hidden bg-blue-50 text-[#0a4ea8] sm:flex">Source prévue · PostgreSQL Render</Badge><Button variant="ghost" size="icon"><Bell /></Button><span className="grid size-9 place-items-center rounded-full bg-blue-50 text-xs font-black text-[#0a4ea8]">AD</span><div className="hidden sm:block"><strong className="block text-xs">Admin FanMilk</strong><span className="text-[10px] text-slate-500">Administrateur</span></div></div></header>
        <div className="p-5 lg:p-8">
          {notice && <div className="mb-5 flex items-center gap-3 rounded-2xl border border-emerald-200 bg-emerald-50 p-4 text-sm font-bold text-emerald-800"><Bell className="size-5" />{notice}<button className="ml-auto" onClick={() => setNotice('')}>×</button></div>}
          <div className="flex flex-col gap-4 md:flex-row md:items-end md:justify-between"><div><p className="text-sm font-black text-[#0a4ea8]">Samedi 29 août 2026</p><h1 className="mt-1 text-4xl font-black text-[#082f70]">Pilotage du réseau</h1><p className="mt-2 text-slate-500">Toutes les données consolidées par Vendor‑Bot.</p></div><div className="flex gap-3"><select className="h-10 rounded-xl border bg-white px-3 text-sm font-bold"><option>Août 2026</option><option>Juillet 2026</option></select><select className="h-10 rounded-xl border bg-white px-3 text-sm font-bold"><option>Tous les dépôts</option><option>SUPER DEPOT</option><option>GERM DOSSEH</option><option>NBUKE RAMCO</option></select></div></div>
          <div id="indicateurs" className="mt-7 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[
            { label: 'Revendeurs actifs', value: '84', note: 'réseau national', icon: Users, tone: 'bg-blue-50 text-blue-700' },{ label: 'CA validé', value: '18,7 M', note: 'FCFA sur la période', icon: CircleDollarSign, tone: 'bg-emerald-50 text-emerald-700' },{ label: 'Difficultés ouvertes', value: '12', note: 'à suivre', icon: AlertTriangle, tone: 'bg-red-50 text-red-700' },{ label: 'Primes attribuées', value: '1,24 M', note: 'FCFA sur la période', icon: Award, tone: 'bg-yellow-50 text-yellow-800' },
          ].map(({ label,value,note,icon: Icon,tone }) => <Card key={label} className="border-0 bg-white ring-blue-950/7"><CardContent className="p-5"><span className={`grid size-11 place-items-center rounded-xl ${tone}`}><Icon className="size-5" /></span><p className="mt-5 text-xs font-bold text-slate-500">{label}</p><p className="mt-1 text-3xl font-black text-[#082f70]">{value}</p><p className="text-xs text-slate-400">{note}</p></CardContent></Card>)}</div>

          <Card id="comptes" className="mt-6 border-0 bg-white ring-blue-950/7"><CardHeader><div className="flex flex-wrap items-center justify-between gap-3"><div><CardTitle>Gestion des comptes utilisateurs</CardTitle><CardDescription>Création, rattachement au dépôt et désactivation</CardDescription></div><Button onClick={() => setShowAccountForm((value) => !value)} className="bg-[#0a4ea8]"><Plus />Créer un compte</Button></div></CardHeader><CardContent>{showAccountForm && <form onSubmit={createAccount} className="mb-6 grid gap-4 rounded-2xl bg-blue-50/70 p-5 sm:grid-cols-2 xl:grid-cols-3"><div><Label>Nom *</Label><Input name="name" required className="mt-2 bg-white" /></div><div><Label>Adresse électronique *</Label><Input name="email" type="email" required className="mt-2 bg-white" /></div><div><Label>Rôle *</Label><select name="role" className="mt-2 h-10 w-full rounded-md border bg-white px-3"><option value="administrateur">Administrateur</option><option value="depositaire">Dépositaire</option><option value="revendeur">Revendeur</option></select></div><div><Label>Dépôt de rattachement</Label><select name="depot" className="mt-2 h-10 w-full rounded-md border bg-white px-3"><option>SUPER DEPOT</option><option>GERM DOSSEH</option><option>NBUKE RAMCO</option></select></div><div><Label>Téléphone revendeur</Label><Input name="phone" placeholder="228XXXXXXXX" className="mt-2 bg-white" /></div><div className="flex items-end gap-2"><Button type="submit">Enregistrer</Button><Button type="button" variant="outline" onClick={() => setShowAccountForm(false)}>Annuler</Button></div></form>}<div className="overflow-x-auto"><Table><TableHeader><TableRow><TableHead>Nom</TableHead><TableHead>Email</TableHead><TableHead>Rôle</TableHead><TableHead>Dépôt</TableHead><TableHead>Statut</TableHead><TableHead className="text-right">Action</TableHead></TableRow></TableHeader><TableBody>{accounts.map((row) => <TableRow key={row.id}><TableCell className="font-bold">{row.name}{row.phone && <small className="block text-slate-400">{row.phone}</small>}</TableCell><TableCell>{row.email}</TableCell><TableCell><Badge variant="outline">{row.role}</Badge></TableCell><TableCell>{row.depot}</TableCell><TableCell><Badge className={row.active ? 'bg-emerald-50 text-emerald-700' : 'bg-slate-100 text-slate-600'}>{row.active ? 'actif' : 'désactivé'}</Badge></TableCell><TableCell className="text-right"><Button size="sm" variant="outline" onClick={() => setAccounts((rows) => rows.map((item) => item.id === row.id ? { ...item, active: !item.active } : item))}>{row.active ? 'Désactiver' : 'Réactiver'}</Button></TableCell></TableRow>)}</TableBody></Table></div></CardContent></Card>

          <Card id="performances" className="mt-6 border-0 bg-white ring-blue-950/7"><CardHeader><CardTitle>Performances et attribution des primes</CardTitle><CardDescription>Règle proposée : score ≥ 80 et CA supérieur à la moyenne du dépôt</CardDescription></CardHeader><CardContent className="overflow-x-auto"><Table><TableHeader><TableRow><TableHead>Revendeur</TableHead><TableHead>Dépôt</TableHead><TableHead>Période</TableHead><TableHead>CA</TableHead><TableHead>Score / moyenne</TableHead><TableHead className="text-right">Prime</TableHead></TableRow></TableHeader><TableBody>{performances.map((row) => <TableRow key={row.seller}><TableCell className="font-bold">{row.seller}</TableCell><TableCell>{row.depot}</TableCell><TableCell>{row.period}</TableCell><TableCell className="font-black">{row.amount} FCFA</TableCell><TableCell><Badge className="bg-blue-50 text-blue-700">{row.score} / {row.average}</Badge></TableCell><TableCell className="text-right"><Button size="sm" onClick={() => { setPrize(row); setPrizeAmount(String(row.suggested)); }} className="bg-yellow-400 text-[#082f70] hover:bg-yellow-300"><Award />Attribuer</Button></TableCell></TableRow>)}</TableBody></Table></CardContent></Card>

          <section className="mt-6 grid gap-6 xl:grid-cols-[.9fr_1.1fr]"><Card id="difficultes" className="border-0 bg-white ring-blue-950/7"><CardHeader><CardTitle>Gestion des difficultés</CardTitle><CardDescription>L’administrateur seul peut mettre à jour l’état</CardDescription></CardHeader><CardContent className="space-y-3">{issues.map((row) => <div key={row.id} className="rounded-2xl border p-4"><div className="flex flex-wrap items-center justify-between gap-2"><span><strong>{row.seller}</strong><small className="ml-2 text-slate-400">{row.depot}</small></span><Badge>{row.state}</Badge></div><p className="mt-2 text-sm font-bold text-[#0a4ea8]">{row.category}</p><p className="mt-1 text-sm text-slate-600">{row.description}</p><div className="mt-3 flex items-center justify-between"><small className="text-slate-400">{row.date}</small>{row.state !== 'resolue' && <Button size="sm" variant="outline" onClick={() => nextIssueState(row.id)}>{row.state === 'ouverte' ? 'Passer en cours' : 'Marquer résolue'}</Button>}</div></div>)}</CardContent></Card><Card id="donnees" className="border-0 bg-white ring-blue-950/7"><CardHeader><CardTitle>Consultation des ventes et stocks</CardTitle><CardDescription>Vue globale · aucune validation possible côté administrateur</CardDescription></CardHeader><CardContent className="overflow-x-auto"><Table><TableHeader><TableRow><TableHead>Type</TableHead><TableHead>Référence</TableHead><TableHead>Revendeur</TableHead><TableHead>Dépôt</TableHead><TableHead>Détail</TableHead><TableHead>Statut</TableHead></TableRow></TableHeader><TableBody>{globalRows.map((row) => <TableRow key={row.ref}><TableCell>{row.type}</TableCell><TableCell className="font-bold">{row.ref}</TableCell><TableCell>{row.seller}</TableCell><TableCell>{row.depot}</TableCell><TableCell>{row.detail}</TableCell><TableCell><Badge variant="outline">{row.status}</Badge></TableCell></TableRow>)}</TableBody></Table></CardContent></Card></section>
        </div>
      </section>
      {prize && <div className="fixed inset-0 z-[100] grid place-items-center bg-[#07162f]/65 p-5 backdrop-blur-sm"><Card className="w-full max-w-lg bg-white"><CardHeader><Award className="size-9 text-yellow-500" /><CardTitle>Attribuer une prime à {prize.seller}</CardTitle><CardDescription>{prize.period} · CA {prize.amount} FCFA · score {prize.score}/100</CardDescription></CardHeader><CardContent><Label>Montant proposé (modifiable)</Label><Input type="number" value={prizeAmount} onChange={(event) => setPrizeAmount(event.target.value)} className="mt-2" /><p className="mt-3 rounded-xl bg-yellow-50 p-3 text-xs text-yellow-900">Calcul proposé : seuil de score atteint et chiffre d’affaires supérieur à la moyenne du dépôt.</p><div className="mt-5 flex justify-end gap-3"><Button variant="outline" onClick={() => setPrize(null)}>Annuler</Button><Button onClick={assignPrize} className="bg-[#0a4ea8]">Enregistrer et notifier</Button></div></CardContent></Card></div>}
    </main>
  );
}
